
// ─── Dil Sistemi ─────────────────────────────────────────────────────────────
var LANG = localStorage.getItem('fu_lang') || 'tr';
var LABELS = {
  tr: {
    secMain:'Ana', secMethod:'Metodoloji', secProd:'Üretkenlik',
    secBook:'Kitap', secKnow:'Bilgi', secSys:'Sistem',
    dashboard:'Dashboard', kpi:'KPI & Metrikler', challenges:'90-Gün Mücadelesi',
    smart:'SMART Hedef Motoru', onething:'ONE Thing', frog:'Eat That Frog',
    timeblock:'Zaman Bloklama', weeklyreview:'Haftalık Review', gtd:'GTD Inbox',
    goals:'Hedefler', todos:'Yapılacaklar', habits:'Alışkanlıklar', routines:'Rutinler',
    library:'Kitap Kütüphanesi', mybooks:'Okuma Listesi', readingplan:'Okuma Planları',
    quotes:'Öz Sözler', journal:'Günlük', principles:'Prensipler',
    coaching:'Koçluk', vault:'Bilgi Kasası', deepwork:'Derin Çalışma',
    sop:'SOP Şablonları', tools:'Odak Araçları', history:'Aktivite',
    undo:'Geri Al', backup:'Yedekle', search:'Ara...',
    confirm:'Silinsin mi?', required:'Zorunlu alanları doldurun.'
  },
  en: {
    secMain:'Main', secMethod:'Methodology', secProd:'Productivity',
    secBook:'Books', secKnow:'Knowledge', secSys:'System',
    dashboard:'Dashboard', kpi:'KPI & Metrics', challenges:'90-Day Challenge',
    smart:'SMART Goal Engine', onething:'ONE Thing', frog:'Eat That Frog',
    timeblock:'Time Blocking', weeklyreview:'Weekly Review', gtd:'GTD Inbox',
    goals:'Goals', todos:'To-Dos', habits:'Habits', routines:'Routines',
    library:'Book Library', mybooks:'Reading List', readingplan:'Reading Plans',
    quotes:'Quotes', journal:'Journal', principles:'Principles',
    coaching:'Coaching', vault:'Knowledge Vault', deepwork:'Deep Work',
    sop:'SOP Templates', tools:'Focus Tools', history:'Activity',
    undo:'Undo', backup:'Backup', search:'Search...',
    confirm:'Delete this item?', required:'Please fill required fields.'
  }
};
function L(key){ return (LABELS[LANG] && LABELS[LANG][key]) || (LABELS.tr[key]) || key; }
function setLang(lang){
  LANG = lang;
  localStorage.setItem('fu_lang', lang);
  document.querySelectorAll('.lang-sw button').forEach(function(b){
    b.className = b.dataset.lang === lang ? 'on' : '';
  });
  var s = document.getElementById('srch');
  if(s) s.placeholder = L('search');
  render();
}
window.setLang = setLang;


var BOOK_CATS=['Temel','Hedef','Disiplin','Sistem','Odak','Alışkanlık','Zaman','Performans','Verimlilik','İlişki'];
var LIB=[
  {id:'b1',t:'The ONE Thing',a:'Gary Keller',cat:0,pages:240,core:true,desc:'Tek en önemli seye odaklanma sanati.'},
  {id:'b2',t:'Atomic Habits',a:'James Clear',cat:5,pages:320,core:true,desc:'1% iyilestirme ve kimlik tabanli alışkanlıklar.'},
  {id:'b3',t:'Deep Work',a:'Cal Newport',cat:4,pages:304,core:true,desc:'Dikkat dagitmadan calismanin ekonomik degeri.'},
  {id:'b4',t:'Getting Things Done',a:'David Allen',cat:6,pages:352,core:true,desc:'GTD: zihinsel yuku sisteme devret.'},
  {id:'b5',t:'The 7 Habits',a:'Stephen Covey',cat:0,pages:432,core:true,desc:'Karakter tabanli etkililik prensipleri.'},
  {id:'b6',t:'Eat That Frog',a:'Brian Tracy',cat:1,pages:144,core:true,desc:'En zor görevi once yap.'},
  {id:'b7',t:'Essentialism',a:'Greg McKeown',cat:0,pages:260,core:false,desc:'Daha az ama daha iyi.'},
  {id:'b8',t:'The Power of Habit',a:'Charles Duhigg',cat:5,pages:371,core:false,desc:'Alışkanlık dongusu: ipucu, rutin, odul.'},
  {id:'b9',t:'Goals!',a:'Brian Tracy',cat:1,pages:288,core:true,desc:'SMART hedef sistemi ve 6 altin kural.'},
  {id:'b10',t:'Make Time',a:'Jake Knapp',cat:6,pages:288,core:false,desc:'Her gun bir odak noktasi sec.'},
  {id:'b11',t:'Indistractable',a:'Nir Eyal',cat:4,pages:288,core:false,desc:'Dikkat dagiticilarla basa cikma.'},
  {id:'b12',t:'Four Thousand Weeks',a:'Oliver Burkeman',cat:6,pages:288,core:false,desc:'80 yil = 4000 hafta. Zaman felsefesi.'},
  {id:'b13',t:'Measure What Matters',a:'John Doerr',cat:3,pages:320,core:true,desc:'OKR sistemi ve Google hikayesi.'},
  {id:'b14',t:'The 80/20 Principle',a:'Richard Koch',cat:7,pages:288,core:true,desc:'Sonuclarin 80i cabanin 20sinden.'},
  {id:'b15',t:'Discipline Equals Freedom',a:'Jocko Willink',cat:2,pages:212,core:true,desc:'Disiplin ozgurlugun temelidir.'},
  {id:'b16',t:'Mindset',a:'Carol Dweck',cat:2,pages:320,core:false,desc:'Buyume zihniyeti vs sabit zihniyet.'},
  {id:'b17',t:'Tiny Habits',a:'BJ Fogg',cat:5,pages:320,core:false,desc:'Küçük baslangiclarin büyük etkisi.'},
  {id:'b18',t:'Building a Second Brain',a:'Tiago Forte',cat:8,pages:272,core:false,desc:'Dijital bilgi yönetimi sistemi.'},
  {id:'b19',t:'Hold Me Tight',a:'Sue Johnson',cat:9,pages:308,core:true,desc:'EFT tabanli cift terapisi.'},
  {id:'b20',t:'The Seven Principles',a:'John Gottman',cat:9,pages:288,core:true,desc:'Başarılı ilişkilerin 7 prensibi.'},
  {id:'b21',t:'Attached',a:'Amir Levine',cat:9,pages:304,core:false,desc:'Baglanma teorisi: guvenli, kacinan, kaygili.'},
  {id:'b22',t:'Grit',a:'Angela Duckworth',cat:2,pages:352,core:false,desc:'Tutku ve azim.'},
  {id:'b23',t:'The Effective Executive',a:'Peter Drucker',cat:3,pages:208,core:true,desc:'Etkililik öğrenilir.'},
  {id:'b24',t:'Peak',a:'Anders Ericsson',cat:7,pages:352,core:false,desc:'Kasitli pratik ve ustalasmak.'},
  {id:'b25',t:'Range',a:'David Epstein',cat:8,pages:352,core:false,desc:'Genelcilerin uzman dunyasinda ustunlugu.'},
];
var RPLANS=[
  {id:'core5',name:'Cekirdek 5',desc:'Keller, Clear, Newport, Tracy, Allen.',books:['b1','b2','b3','b6','b4']},
  {id:'rel',name:'İlişki & Bag',desc:'Gottman, Johnson, Levine.',books:['b19','b20','b21']},
  {id:'disc',name:'Disiplin & Zihin',desc:'Willink, Dweck, Duckworth.',books:['b15','b16','b22']},
  {id:'sys',name:'Sistem Kurma',desc:'Drucker, Doerr, Koch.',books:['b23','b13','b14']},
  {id:'habit',name:'Alışkanlık',desc:'Atomic Habits ekolu.',books:['b2','b8','b17']},
  {id:'focus',name:'Derin Odak',desc:'Newport ekolu.',books:['b3','b11']},
];
var CH_TPLS=[
  {id:'no-sugar',name:'Seker Yok',cat:'Sağlık',desc:'90 gun ilave seker tuketme.',diff:'hard',xp:300},
  {id:'cold',name:'Soguk Dus',cat:'Sağlık',desc:'Her sabah 60sn soguk dus.',diff:'medium',xp:200},
  {id:'read',name:'Her Gün Oku',cat:'Gelişim',desc:'Günlük en az 20 sayfa.',diff:'easy',xp:150},
  {id:'no-social',name:'Sosyal Medya Detoks',cat:'Odak',desc:'90 gun sosyal medyasiz.',diff:'extreme',xp:500},
  {id:'workout',name:'Antrenman',cat:'Sağlık',desc:'Haftada 4 gun 30dk.',diff:'medium',xp:250},
  {id:'meditate',name:'Meditasyon',cat:'Zihin',desc:'Günlük 10dk meditasyon.',diff:'easy',xp:150},
  {id:'deepwork',name:'Derin Çalışma',cat:'Odak',desc:'Günlük 2 saat kesintisiz.',diff:'hard',xp:300},
  {id:'custom',name:'Ozel Mücadele',cat:'Ozel',desc:'Kendi meydan okumani belirle.',diff:'medium',xp:250},
];
var DIFF={easy:{l:'Kolay',c:'p-green'},medium:{l:'Orta',c:'p-orange'},hard:{l:'Zor',c:'p-red'},extreme:{l:'Ekstrem',c:'p-purple'}};
var SOUNDS=[
  {name:'Yagmur',url:'https://cdn.pixabay.com/download/audio/2022/05/16/audio_1ba1e93e9c.mp3',emoji:'🌧'},
  {name:'Kafe',url:'https://cdn.pixabay.com/download/audio/2021/08/09/audio_dc39bde808.mp3',emoji:'☕'},
  {name:'Orman',url:'https://cdn.pixabay.com/download/audio/2021/09/06/audio_c4ccf31f16.mp3',emoji:'🌲'},
  {name:'Deniz',url:'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0c6ff1bcc.mp3',emoji:'🌊'},
  {name:'Beyaz Gurultu',url:'https://cdn.pixabay.com/download/audio/2022/03/10/audio_4b2e3aeaaa.mp3',emoji:'🔊'},
];
var GOAL_CATS=['İş','Kişisel','Sağlık','Finans','Gelişim','İlişki','Eğitim','Diğer'];
var GOAL_CC={İş:'var(--blue)',Kişisel:'var(--purple)',Sağlık:'var(--green)',Finans:'var(--orange)',Gelişim:'var(--teal)',İlişki:'#ff6b9d',Eğitim:'var(--blue)',Diğer:'var(--t3)'};
var GOAL_CB={İş:'var(--bl)',Kişisel:'var(--pl)',Sağlık:'var(--gl)',Finans:'var(--ol)',Gelişim:'var(--tl)',İlişki:'rgba(255,107,157,.1)',Eğitim:'var(--bl)',Diğer:'var(--s2)'};

var INIT={
  goals:[{id:1,title:'Ingilizce C1 Sertifikasyonu',desc:'Uluslararasi projelerde liderlik.',cat:'Gelişim',quarter:'Q1',frog:true,deadline:'2026-12-31',measurable:'IELTS 7.5',steps:[{id:101,t:'Kursa kayit ol',done:true},{id:102,t:'Haftalık essay yaz',done:false}],notes:'',status:'active',createdAt:'2026-01-01'}],
  todos:[{id:11,text:'Raporu teslim et',priority:'urgent',category:'İş',end:'2026-04-15',done:false},{id:12,text:'Haftalık planlama',priority:'high',category:'İş',end:'',done:false}],
  kpis:[{id:201,name:'Haftalık Odak Saati',unit:'saat',target:40,current:28,cat:'İş',hist:[22,25,28]},{id:202,name:'Günlük Sayfa',unit:'sayfa',target:20,current:14,cat:'Gelişim',hist:[8,12,14]}],
  mybooks:[],
  readingPlan:null,
  habits:[{id:301,name:'Sabah Meditasyonu',color:'green',checkins:[]},{id:302,name:'20 Sayfa Okuma',color:'blue',checkins:[]},{id:303,name:'Egzersiz',color:'orange',checkins:[]}],
  routines:{
    daily:[{id:61,t:'Sabah meditasyon (10dk)',last:null},{id:62,t:'Su ic (500ml)',last:null},{id:63,t:'Günlük planlama',last:null}],
    weekly:[{id:71,t:'Haftalık review',last:null}],
    monthly:[{id:81,t:'KPI degerlendirmesi',last:null}],
    quarterly:[],yearly:[]
  },
  challenges:[],
  gtdInbox:[{id:401,text:'Yeni proje fikirini degerlendirmek',status:'inbox',addedAt:'2026-03-18'}],
  timeblocks:{},
  weeklyReview:{done:'',missed:'',why:'',next:'',oneThingNext:'',updatedAt:''},
  oneThing:{task:'',date:''},
  sops:[{id:501,title:'Haftalık Planlama SOP',steps:['Önceki haftayi gözden geçir','KPI güncelle','ONE Thing belirle','Zaman bloklama yap']}],
  quotes:[
    {id:1001,text:'Bir anda bir sey. Iyi yap.',author:'Marcus Aurelius',cat:'Odak'},
    {id:1002,text:'Konsantrasyon, dahiligin bedeli.',author:'Robert J. Ringer',cat:'Odak'},
    {id:1003,text:'Basiret, nereye dikkat ettigini bilmektir.',author:'William James',cat:'Odak'},
    {id:1004,text:'Coklu görev bir mit; dikkat parcalanir, verim duserr.',author:'Cal Newport',cat:'Odak'},
    {id:1005,text:'Dikkatini kontrolden cikarmak, hayatini kontrolden cikarmaktir.',author:'Mihaly Csikszentmihalyi',cat:'Odak'},
    {id:1006,text:'Odak, hayir demekle ilgilidir.',author:'Steve Jobs',cat:'Odak'},
    {id:1007,text:'Sessizlik zayifligin degil, odagin sesidir.',author:'Naval Ravikant',cat:'Odak'},
    {id:1008,text:'En büyük kahraman dikkatini kaybetmeyen kisidir.',author:'Marcus Aurelius',cat:'Odak'},
    {id:1011,text:'Disiplin, arzu ile başarı arasindaki koprudur.',author:'Jim Rohn',cat:'Disiplin'},
    {id:1012,text:'Özgürlük disiplinin meyvesidir.',author:'Jocko Willink',cat:'Disiplin'},
    {id:1013,text:'Motivasyon seni başlatır; alışkanlık seni ilerletir.',author:'Jim Ryun',cat:'Disiplin'},
    {id:1014,text:'Kendini yönetemeyen bakalari tarafindan yonetilir.',author:'Seneca',cat:'Disiplin'},
    {id:1015,text:'Her gun küçük bir eylem, zamanla olaganustu sonuclar uretir.',author:'James Clear',cat:'Disiplin'},
    {id:1016,text:'Irade, her kullanildikca guclenen bir kasdir.',author:'Kelly McGonigal',cat:'Disiplin'},
    {id:1017,text:'Disiplin, istedigin hayatla katlandiklarin arasindaki seci istir.',author:'Anon',cat:'Disiplin'},
    {id:1018,text:'Acidan kac, hayal kirikligina kos; sonunda ikisini de bulursun.',author:'Haruki Murakami',cat:'Disiplin'},
    {id:1021,text:'Net bir hedef, yolu kendiliğinden aydinlatir.',author:'Brian Tracy',cat:'Hedef'},
    {id:1022,text:'Hedefe ulasma yuzde sekseni kendini o hedefe inandirmaktir.',author:'Marissa Mayer',cat:'Hedef'},
    {id:1023,text:'Yazılı hedefleri olanlar yazmayanlara gore dokuz kat daha başarılıdir.',author:'Gail Matthews',cat:'Hedef'},
    {id:1024,text:'Büyük bir neden, küçük engelleri otomatik astirir.',author:'Viktor Frankl',cat:'Hedef'},
    {id:1025,text:'Hedefini bilmiyorsan, herhangi bir yol seni oraya goturur.',author:'Lewis Carroll',cat:'Hedef'},
    {id:1026,text:'En tehlikeli an, hedefe yaklastiginda olandir; o an gevsersin.',author:'Napoleon Bonaparte',cat:'Hedef'},
    {id:1027,text:'Kısa vadeli rahatlik uzun vadeli başarınin dusmanidir.',author:'Shane Parrish',cat:'Hedef'},
    {id:1028,text:'Hedefin boyutu, takim kalitenin sinyalidir.',author:'Peter Thiel',cat:'Hedef'},
    {id:1031,text:'Kendini dününden bir milimetre daha iyi yap.',author:'Kaizen',cat:'Gelişim'},
    {id:1032,text:'Bir kitap okumayan okumayi bilmeyenden farkli degildir.',author:'Mark Twain',cat:'Gelişim'},
    {id:1033,text:'Öğrenmediğimiz gun kayip gundur.',author:'Charlie Munger',cat:'Gelişim'},
    {id:1034,text:'Zihinsel modellerini genis tut; her alan baska bir merceq verir.',author:'Charlie Munger',cat:'Gelişim'},
    {id:1035,text:'En iyi yatırım kendine yaptigindir.',author:'Warren Buffett',cat:'Gelişim'},
    {id:1036,text:'Her uzman bir zamanlar acemiydi. Baslayan kazanir.',author:'Helen Hayes',cat:'Gelişim'},
    {id:1037,text:'Rahatsızlık olmadan büyüme olmaz.',author:'Brian Tracy',cat:'Gelişim'},
    {id:1038,text:'Öğrenmek icin utancini bir kenara birak.',author:'Confucius',cat:'Gelişim'},
    {id:1039,text:'Hatalar bedava eğitimdir.',author:'Naval Ravikant',cat:'Gelişim'},
    {id:1041,text:'Zaman en değerli kaynagindir cunku geri dondurulemez.',author:'Peter Drucker',cat:'Zaman'},
    {id:1042,text:'Bugünu yasayan yarina hazirdır.',author:'Seneca',cat:'Zaman'},
    {id:1043,text:'Sahip oldugun tek sey bu andir.',author:'Eckhart Tolle',cat:'Zaman'},
    {id:1044,text:'Geçmişi değiştiremezsin; gelecegi ancak simdiki eylemle sekillendirirsin.',author:'Marcus Aurelius',cat:'Zaman'},
    {id:1045,text:'Zaman yönetimi aslinda oz yönetimidir.',author:'Stephen Covey',cat:'Zaman'},
    {id:1046,text:'Erteleme, zamanın en ciddi hırsızıdır.',author:'Victor Hugo',cat:'Zaman'},
    {id:1047,text:'Her dakika planlamak saatlerce tasarrufu sağlar.',author:'Benjamin Franklin',cat:'Zaman'},
    {id:1048,text:'Acele et, ama kosma.',author:'John Wooden',cat:'Zaman'},
    {id:1051,text:'Insanlari yonet, surecleri yonet; ikisini karistirma.',author:'W. Edwards Deming',cat:'Liderlik'},
    {id:1052,text:'İyi lider konuşmadan önce dinler.',author:'Richard Branson',cat:'Liderlik'},
    {id:1053,text:'Beklenti bir strateji degildir.',author:'Patrick Lencioni',cat:'Liderlik'},
    {id:1054,text:'Küçük eylemler büyük ornek olur.',author:'John C. Maxwell',cat:'Liderlik'},
    {id:1055,text:'Ekibini bugünde en iyisi olarak degil gelecekte olabilecegi icin ise al.',author:'Jack Welch',cat:'Liderlik'},
    {id:1056,text:'Guclu liderler zaferleri dagitin, yenilgileri sahiplenir.',author:'Jocko Willink',cat:'Liderlik'},
    {id:1057,text:'Güveni inşa etmek yıllar alır; kaybetmek saniyeler.',author:'Warren Buffett',cat:'Liderlik'},
    {id:1061,text:'Başarı, heyecanini kaybetmeden hayal kirikligından hayal kiriklgina gitmektir.',author:'Winston Churchill',cat:'Başarı'},
    {id:1062,text:'Başarıyi tanimla, sonra geri sarip yolu ciz.',author:'Tony Robbins',cat:'Başarı'},
    {id:1063,text:'Her büyük başarınin gerisinde başarılı bir alışkanlık dizisi vardir.',author:'Aristotle',cat:'Başarı'},
    {id:1064,text:'Mukemmel, iyinin dusmanidir.',author:'Voltaire',cat:'Başarı'},
    {id:1065,text:'Yavaslayan kazanir; bitmek uzere olan kosarak biter.',author:'Robert Maurer',cat:'Başarı'},
    {id:1066,text:'Sistem kur; sonuclara degil sisteme guven.',author:'James Clear',cat:'Başarı'},
    {id:1067,text:'Baslangiclar gurus gerektirir; bitis kararliliik.',author:'Anon',cat:'Başarı'},
    {id:1068,text:'En iyi an iki yil once baslamakti; ikinci en iyi an simdi.',author:'Cin Atasyozu',cat:'Başarı'},
    {id:1071,text:'Gelecegi tahmin etmenin en iyi yolu onu yaratmaktir.',author:'Alan Kay',cat:'Vizyon'},
    {id:1072,text:'Büyük ruzgarlara karsi gobegi sil olmak yerine kanat ac.',author:'Rumi',cat:'Vizyon'},
    {id:1073,text:'Imkansiz sadece denenmedik demektir.',author:'Anon',cat:'Vizyon'},
    {id:1074,text:'Hayalinle dalga gecenlere kulak asma; onlar senin gosterinin biletini alamazlar.',author:'Anon',cat:'Vizyon'},
    {id:1075,text:'On yil once büyük gorunen hedef, simdi standart sayilir.',author:'Peter Thiel',cat:'Vizyon'},
    {id:1076,text:'Düşünceler dunyayi değiştirir.',author:'Steve Jobs',cat:'Vizyon'},
    {id:1077,text:'Büyük dusunceler büyük insanlari ceker.',author:'Jim Rohn',cat:'Vizyon'},
    {id:1081,text:'Zihin, ateş gibidir: yakiti olmadan soner.',author:'Plutarch',cat:'Zihin'},
    {id:1082,text:'Kalabalık zihin, uretken zihin degildir.',author:'David Allen',cat:'Zihin'},
    {id:1083,text:'Düşüncelerini kontrol edemezsin; ama onlara katilmamayi secebilirsin.',author:'Viktor Frankl',cat:'Zihin'},
    {id:1084,text:'Zihninizi bosaltmak icin sistemlere guvenin.',author:'David Allen',cat:'Zihin'},
    {id:1085,text:'Merak, öğrenmenin yegane motorudur.',author:'Albert Einstein',cat:'Zihin'},
    {id:1086,text:'Konfor zonu beyin için zehirdir.',author:'David Eagleman',cat:'Zihin'},
    {id:1087,text:'Endişe, hayal gücünün yanlış kullanilmasidir.',author:'Anon',cat:'Zihin'},
    {id:1088,text:'Uyku, zihnin bakımıdır.',author:'Matthew Walker',cat:'Zihin'},
    {id:1091,text:'Cesaret korkunun yokluğu değil, korkuya ragmen ilerleme kararidir.',author:'Mark Twain',cat:'Cesaret'},
    {id:1092,text:'Hayir demek de bir cesaret ister.',author:'Paulo Coelho',cat:'Cesaret'},
    {id:1093,text:'En büyük risk, hic risk almamaktir.',author:'Mark Zuckerberg',cat:'Cesaret'},
    {id:1094,text:'Başaramamanın acısı denememenin acisinin yuzde birinden azdir.',author:'Jim Carrey',cat:'Cesaret'},
    {id:1095,text:'Beyin tehlikeyi büyütür, cesaret onu gercek boyutuna indirir.',author:'Anon',cat:'Cesaret'},
    {id:1096,text:'Korkuya teslim olmak, hayatin en az yayandiginda olur.',author:'Eleanor Roosevelt',cat:'Cesaret'},
    {id:1097,text:'Ölçemedin seyi gelistiremezsin.',author:'Peter Drucker',cat:'Yönetim'},
    {id:1098,text:'Basit kal, ahmak gibi kal.',author:'Steve Jobs',cat:'Vizyon'},
    {id:1099,text:'80 sonuç 20 kaynaktan gelir. Doğruyu seç.',author:'Richard Koch',cat:'Üretkenlik'},
    {id:1100,text:'Verimli olmak, doğru şeyleri yapmaktır. Etkin olmak, şeyleri doğru yapmaktır.',author:'Peter Drucker',cat:'Üretkenlik'},
    {id:1101,text:'Yuzde yuz katilmadigin seylere yuzde yuz katilma.',author:'Naval Ravikant',cat:'Cesaret'},
    {id:1102,text:'Hayatta iki tur insan vardir: olaylar yaratan ve olan olaylara tepki verenler.',author:'Jim Rohn',cat:'Cesaret'},
    {id:1103,text:'Düşünmeden öğrenme emektir, ogenmeden dusunmek ise tehlike.',author:'Confucius',cat:'Zihin'},
    {id:1104,text:'Mukemmelin dusmani iyidir; iyinin dusmani ise hicbir sey yapmamaktir.',author:'Voltaire',cat:'Disiplin'},
    {id:1105,text:'Basit olmak zordur; o yuzden cogu insan karmakasikliga siginar.',author:'Steve Jobs',cat:'Vizyon'},
    {id:1106,text:'Para kazanmak kolay; kazandiktan sonra akilli kalmak asil mesele.',author:'Charlie Munger',cat:'Yönetim'},
    {id:1107,text:'Iyi bir sistem kurduğunda, kotu gunlerde bile ilerlemeye devam edersin.',author:'James Clear',cat:'Disiplin'},
    {id:1108,text:'Öğrenmenin en iyi yolu ogretmektir.',author:'Richard Feynman',cat:'Gelişim'},
    {id:1109,text:'Uyku en ucuz performans arttiricidir.',author:'Matthew Walker',cat:'Zihin'},
    {id:1110,text:'Harika isler yapmanin tek yolu yaptigin isi sevmektir.',author:'Steve Jobs',cat:'Başarı'},
    {id:1111,text:'Kitaplar zaman makinesidir; baska birinin 30 yilini 6 saatte yasarsın.',author:'Naval Ravikant',cat:'Gelişim'},
    {id:1112,text:'Enerjini takip et, zamanini degil.',author:'Naval Ravikant',cat:'Zaman'},
    {id:1113,text:'Her insan kendi hayatinin yazari; bazi insanlar sadece virgul koymakla yetinir.',author:'Anon',cat:'Cesaret'},
    {id:1114,text:'Duygularini denetleyemezsen kararlarini da denetleyemezsin.',author:'Daniel Kahneman',cat:'Zihin'},
    {id:1115,text:'Başarı ucgen degil, dongu gerektirir: yap, ol c, duzelт.',author:'Anon',cat:'Başarı'},
    {id:1116,text:'Sadece sonuclara bakma; sistemi degerlendير.',author:'W. Edwards Deming',cat:'Yönetim'},
    {id:1117,text:'Rekabet yerine monopol kur; tek oldugun yerde yaris yoktur.',author:'Peter Thiel',cat:'Vizyon'},
    {id:1118,text:'Her gece yatmadan once sorular: Bugün kime deger kattim? Bugün ne öğrendim?',author:'Tony Robbins',cat:'Gelişim'},
    {id:1119,text:'Verimlilik bir his degil; bir ölçümdur.',author:'Peter Drucker',cat:'Üretkenlik'}
  ],
  journal:[{id:51,date:'2026-03-18',cat:'Sukran',text:'Bugün odaklanmayi basardim.'}],
  principles:[{id:91,type:'Vizyon',text:'Her gun %1 daha iyi olmak.'},{id:92,type:'Kural',text:'Ilk 2 saatimi derin çalışma icin koru.'}],
  coaching:[{id:101,title:'OKR Sistemi',text:'Objective + Key Results. Her çeyrek 1 büyük hedef.',cat:'Yontem'}],
  vault:[],questions:[{id:1,text:'Korkmasaydim bugün ne yapardim?'}],
  generalNotes:[],
  wisdomQuotes:[],
  /* D10.2 — Bilgelik gösterim/rotasyon ayarları (additive; D10.1 modeline dokunmaz) */
  wisdomSettings:{enabled:false,displayMode:'card',rotationMode:'pageopen',favoritesOnly:false,
    selectedCategories:[],selectedLanguages:[],position:'hero',animation:'fade',
    showAuthor:true,showCategory:true,showProgress:false,pinMode:'rotate',pinnedQuoteId:null,
    contextAware:false,respectPriority:true,avoidRecentlyShown:true},
  /* D10.5.1 — İlkelerim yönetim ekranı ayarları (gösterim/rotasyon ayarı DEĞİL; D10.5.2'ye ait alanlar burada YOK) */
  principleSettings:{defaultSort:'priority',showArchived:false,compactView:false},
  compat:{mode:'individual',answers:{},partnerAnswers:{}},
  savedResources:{},
  logs:[],scratch:'',
  stats:{xp:120,level:1,totalFocus:0,todayFocus:0},
  vol:0.6,activeSound:null,deepWorkSessions:0,
};

